language: python
python:
  - "3.5"
  - "3.6"
  
services:
  - docker

before_install:
  - docker run --name couchdb -p 5984:5984 -d couchdb:2
  - docker ps
  
install:
  - pip install -e .
  - pip install nose asynctest

script:
  - nosetests
